### ISSUE TITLE
Update docs on phone location value defaults in README

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/radar-android-phone#42]
- [ ] update phone location defaults (currently not correct) as these were increased
- [ ] add settings for changing relative to the absolute location i.e. `phone_relative_location` = false

**Comment by nivemaham** [comment]
@afolarin FYI, all of the plugins have been now moved to https://github.com/RADAR-base/radar-commons-android to reduce overhead on working multiple repos. 
Although this is the source-code of the currently published app on playstore. Good point on the docs. Maybe we should check what is mentioned on the new version as well.
