### ISSUE TITLE
Add Hash of Bluetooth MAC address for nearby Bluetooth Device Count

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/radar-android-phone#43]
This is a future (though often requested extension to Bluetooth device counts). Having the hash of the nearby device MAC address would allow semantics of which devices in the snapshot sample are new or previously encountered.

Comments on how this might be implemented from @blootsvoets .

> We’d welcome a plugin implementing that behaviour (https://github.com/RADAR-base/radar-commons-android/blob/master/plugins/radar-android-phone/src/main/java/org/radarbase/passive/phone/PhoneBluetoothManager.kt would be a good place to start). The plugin should only send the hashed MAC address (using https://github.com/RADAR-base/radar-commons-android/blob/master/radar-commons-android/src/main/java/org/radarbase/android/util/HashGenerator.kt) to avoid privacy leaks from the participant or passers-by, unless some explicit configuration is given to expose certain MAC addresses known to belong to the participant.

**Comment by blootsvoets** [comment]
Migrated to RADAR-base/radar-commons-android#253
